/**
 * FE-1's build gates that are file facts rather than behaviour.
 *
 * F13 in particular is the one that stops the store swap from half-reverting:
 * as long as a local-persistence dependency is still reachable from /notes,
 * someone will reach for it the next time the network is inconvenient, and the
 * module quietly grows a second source of truth.
 */

import { describe, expect, it } from 'vitest';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = 'src/pages/notes';

function sourceFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) return sourceFiles(path);
    return /\.(ts|tsx)$/.test(path) ? [path] : [];
  });
}

describe('F13 — the notes module has no local persistence', () => {
  const files = sourceFiles(ROOT);

  it('mentions idb-keyval nowhere, not even in a comment', () => {
    const offenders = files.filter((file) => readFileSync(file, 'utf8').includes('idb-keyval'));
    expect(offenders, offenders.join(', ')).toEqual([]);
  });

  it('does not write notes to localStorage either', () => {
    // The store's only browser storage is the one-time legacy-cleanup flag, and
    // that lives outside this directory.
    const offenders = files.filter((file) => /localStorage\.setItem/.test(readFileSync(file, 'utf8')));
    expect(offenders, offenders.join(', ')).toEqual([]);
  });

  it('has no client-side seed module', () => {
    expect(files.some((file) => file.endsWith('seed.ts'))).toBe(false);
    // An import of one, not the word — `apiClient` names the deleted function in
    // a comment explaining what replaced it, and that comment is worth keeping.
    const offenders = files.filter((file) => /from '[^']*_lib\/seed'/.test(readFileSync(file, 'utf8')));
    expect(offenders, offenders.join(', ')).toEqual([]);
  });
});

describe('F1 — api-types.ts is generated, not authored', () => {
  const source = readFileSync(join(ROOT, '_lib/api-types.ts'), 'utf8');

  it('still carries its generator banner', () => {
    expect(source.slice(0, 400)).toMatch(/auto-generated by openapi-typescript/i);
    expect(source.slice(0, 400)).toMatch(/do not make direct changes/i);
  });

  it('is imported only by the client and the components that render its rows', () => {
    // Anything else reaching for the generated shapes is a sign the hand-written
    // `Note` type is being bypassed.
    const importers = sourceFiles(ROOT).filter((file) =>
      /from '(\.\/|@\/pages\/notes\/_lib\/)api-types'/.test(readFileSync(file, 'utf8')),
    );
    expect(importers.length).toBeLessThanOrEqual(4);
  });
});
