import type { AuditEntry, ClientRequest, CloseCase, Mandate } from './types';

// Mock seed data — stands in for the agent backend. All case/request content is
// backend data (arrives pre-composed); UI chrome is translated via i18n.

export const MOCK_MANDATES: Mandate[] = [
  { id: 'm-mueller', name: 'Müller Maschinenbau GmbH', deadline: '2026-07-28', risk: 'high', missing: '3 receipts · VAT check' },
  { id: 'm-hansa', name: 'Hansa Logistik AG', deadline: '2026-07-29', risk: 'high', missing: '2 bank matches' },
  { id: 'm-bergmann', name: 'Bergmann & Söhne KG', deadline: '2026-07-30', risk: 'medium', missing: '1 receipt' },
  { id: 'm-kranich', name: 'Kranich Bau GmbH', deadline: '2026-07-31', risk: 'medium', missing: 'Accrual review' },
  { id: 'm-nordwind', name: 'Nordwind Energie SE', deadline: '2026-07-31', risk: 'low', missing: '—' },
  { id: 'm-falke', name: 'Falke IT Services GmbH', deadline: '2026-08-03', risk: 'low', missing: '—' },
  { id: 'm-linde', name: 'Linde Gastronomie e.K.', deadline: '2026-08-04', risk: 'medium', missing: '1 duplicate booking' },
  { id: 'm-weber', name: 'Weber Textil GmbH & Co. KG', deadline: '2026-08-05', risk: 'low', missing: '—' },
  { id: 'm-adler', name: 'Adler Immobilien GmbH', deadline: '2026-08-06', risk: 'low', missing: '—' },
  { id: 'm-stein', name: 'Steinmetz Consulting UG', deadline: '2026-08-07', risk: 'low', missing: '—' },
];

export const MOCK_CASES: CloseCase[] = [
  {
    id: 'c-1001',
    mandateId: 'm-mueller',
    transactionRef: 'BK-2026-07-0342',
    amount: 1846.32,
    currency: 'EUR',
    category: 'missing_receipt',
    problem: 'Outgoing payment of €1,846.32 to "Hoffmann Werkzeuge" has no matching receipt in the DMS.',
    suspectedCause: 'Supplier invoice was sent to a personal inbox and never uploaded.',
    source: 'DATEV Unternehmen online · bank feed line 342',
    ruleCheck: 'Receipt-match rule R-104: payment > €150 requires linked document',
    ruleCheckPassed: false,
    proposedAction: 'Draft a document request to the client bundling this and 2 further missing receipts.',
    confidence: 91,
    status: 'pending',
    modelVersion: 'pincer-close-2.3.1',
  },
  {
    id: 'c-1002',
    mandateId: 'm-mueller',
    transactionRef: 'ER-2026-07-0117',
    amount: 2380.0,
    currency: 'EUR',
    category: 'vat_mismatch',
    problem: 'Invoice ER-0117 books 19% VAT but the supplier is registered in Austria (reverse charge expected).',
    suspectedCause: 'OCR captured the German VAT line of a mixed invoice; §13b reverse charge applies.',
    source: 'Invoice PDF, page 2 · VIES check on ATU66992207',
    ruleCheck: 'VAT rule R-221: EU supplier + service = reverse charge §13b UStG',
    ruleCheckPassed: true,
    proposedAction: 'Rebook to account 3123 (SKR04) with 0% input VAT and reverse-charge flag.',
    confidence: 94,
    status: 'pending',
    modelVersion: 'pincer-close-2.3.1',
  },
  {
    id: 'c-1003',
    mandateId: 'm-hansa',
    transactionRef: 'BK-2026-07-0518',
    amount: 12400.0,
    currency: 'EUR',
    category: 'unmatched_payment',
    problem: 'Incoming payment of €12,400.00 cannot be matched to any open receivable.',
    suspectedCause: 'Payment likely covers invoices RE-2026-231 and RE-2026-235 combined, minus 2% Skonto.',
    source: 'Bank feed · open-items list (OPOS) as of 23 Jul',
    ruleCheck: 'Matching rule R-310: amount within Skonto tolerance of invoice group',
    ruleCheckPassed: true,
    proposedAction: 'Clear RE-2026-231 + RE-2026-235 against the payment and book €253.06 Skonto expense.',
    confidence: 88,
    status: 'pending',
    modelVersion: 'pincer-close-2.3.1',
  },
  {
    id: 'c-1004',
    mandateId: 'm-hansa',
    transactionRef: 'BK-2026-07-0533',
    amount: 980.5,
    currency: 'EUR',
    category: 'unmatched_payment',
    problem: 'Outgoing SEPA payment of €980.50 references an unknown creditor "TransCargo Ltd".',
    suspectedCause: 'New supplier not yet created in the creditor master data.',
    source: 'Bank feed line 533 · creditor master search',
    ruleCheck: 'Master-data rule R-115: payee must exist as creditor',
    ruleCheckPassed: false,
    proposedAction: 'Create creditor 71204 "TransCargo Ltd" and post payment against it — needs human confirmation.',
    confidence: 62,
    status: 'pending',
    modelVersion: 'pincer-close-2.3.1',
  },
  {
    id: 'c-1005',
    mandateId: 'm-bergmann',
    transactionRef: 'BK-2026-07-0201',
    amount: 445.9,
    currency: 'EUR',
    category: 'missing_receipt',
    problem: 'Card payment of €445.90 at "Hotel Sonnenhof" has no receipt.',
    suspectedCause: 'Travel expense — receipt probably still with the traveling employee.',
    source: 'Credit-card feed · DMS full-text search (no hit)',
    ruleCheck: 'Receipt-match rule R-104: payment > €150 requires linked document',
    ruleCheckPassed: false,
    proposedAction: 'Add to the document request for Bergmann & Söhne (travel receipts section).',
    confidence: 89,
    status: 'pending',
    modelVersion: 'pincer-close-2.3.1',
  },
  {
    id: 'c-1006',
    mandateId: 'm-linde',
    transactionRef: 'ER-2026-07-0092',
    amount: 312.75,
    currency: 'EUR',
    category: 'duplicate_booking',
    problem: 'Invoice "Getränke Braun 07/26" appears booked twice (ER-0092 and ER-0088).',
    suspectedCause: 'Invoice arrived by e-mail and again by post; both copies were scanned.',
    source: 'Duplicate detector · document hash + amount + supplier match',
    ruleCheck: 'Duplicate rule R-402: same supplier, amount, invoice number within 30 days',
    ruleCheckPassed: true,
    proposedAction: 'Reverse booking ER-2026-07-0092 (keep ER-0088 as original).',
    confidence: 97,
    status: 'pending',
    modelVersion: 'pincer-close-2.3.1',
  },
  {
    id: 'c-1007',
    mandateId: 'm-kranich',
    transactionRef: 'AN-2026-07-0009',
    amount: 18500.0,
    currency: 'EUR',
    category: 'accrual_needed',
    problem: 'Subcontractor work completed in July (site log) but no invoice received — accrual required.',
    suspectedCause: 'Subcontractor "Elektro Roth" typically invoices 4–6 weeks after completion.',
    source: 'Site documentation portal · order 4711 · historical invoicing pattern',
    ruleCheck: 'Accrual rule R-510: delivered-not-invoiced > €5,000 at period end',
    ruleCheckPassed: true,
    proposedAction: 'Post accrual of €18,500.00 to 3070/4890 (SKR04), auto-reverse on 1 Aug.',
    confidence: 78,
    status: 'pending',
    modelVersion: 'pincer-close-2.3.1',
  },
  {
    id: 'c-1008',
    mandateId: 'm-mueller',
    transactionRef: 'ER-2026-07-0134',
    amount: 89.99,
    currency: 'EUR',
    category: 'wrong_account',
    problem: 'Software subscription "Figma" booked to 6815 (office supplies) instead of 6837 (software licenses).',
    suspectedCause: 'Default account of the creditor is outdated.',
    source: 'Booking journal · account-usage model for mandate',
    ruleCheck: 'Account rule R-330: SaaS creditors map to 6837 (SKR04)',
    ruleCheckPassed: true,
    proposedAction: 'Rebook €89.99 from 6815 to 6837 and update the creditor default account.',
    confidence: 96,
    status: 'pending',
    modelVersion: 'pincer-close-2.3.1',
  },
];

export const MOCK_REQUESTS: ClientRequest[] = [
  {
    id: 'r-501',
    mandateId: 'm-mueller',
    recipient: 'buchhaltung@mueller-maschinenbau.de',
    channel: 'email',
    title: 'Missing documents for the July close',
    body: 'Dear Ms Krause, for the July month-end close we are still missing the documents listed below. You can reply directly to this e-mail or upload them to the portal.',
    bundledItems: [
      'Receipt for payment to Hoffmann Werkzeuge, €1,846.32 (24 Jul)',
      'Receipt for card payment Hotel Sonnenhof, €445.90 (18 Jul)',
      'Invoice for standing order "Halle Süd Miete", €2,100.00 (01 Jul)',
    ],
    status: 'draft',
  },
  {
    id: 'r-502',
    mandateId: 'm-bergmann',
    recipient: '+49 171 5550132 (J. Bergmann)',
    channel: 'whatsapp',
    title: 'Travel receipts July',
    body: 'Hello Mr Bergmann, one short reminder for the July close — we still need the hotel receipt from the Sonnenhof stay. A photo of the receipt is enough.',
    bundledItems: ['Hotel Sonnenhof receipt, €445.90 (18 Jul)'],
    status: 'draft',
  },
  {
    id: 'r-503',
    mandateId: 'm-hansa',
    recipient: 'Finance channel · Hansa Logistik',
    channel: 'teams',
    title: 'Confirmation of new creditor TransCargo',
    body: 'Hi team, we found a payment to "TransCargo Ltd" that is not yet in your supplier list. Could you confirm this is a legitimate new supplier and share the master data (address, VAT ID, IBAN)?',
    bundledItems: ['Supplier confirmation TransCargo Ltd, €980.50 (22 Jul)'],
    status: 'draft',
  },
  {
    id: 'r-504',
    mandateId: 'm-nordwind',
    recipient: 'portal · Nordwind Energie SE',
    channel: 'portal',
    title: 'June close documentation',
    body: 'The June close package is complete and available in the portal.',
    bundledItems: ['June close report', 'BWA 06/2026'],
    status: 'sent',
  },
  {
    id: 'r-505',
    mandateId: 'm-linde',
    recipient: '+380 67 555 0199 (O. Linde)',
    channel: 'viber',
    title: 'Cash report week 29',
    body: 'Reminder: the cash report for week 29 has not been uploaded yet.',
    bundledItems: ['Cash report week 29'],
    status: 'sent',
  },
];

export const MOCK_AUDIT: AuditEntry[] = [
  {
    id: 'a-9004',
    timestamp: '2026-07-23T16:42:00Z',
    action: 'case.approved',
    detail: 'Nordwind Energie SE · ER-2026-06-0301 · rebooked 6600→6805',
    outcome: 'approved',
    payload: {
      mandate: 'Nordwind Energie SE',
      transactionRef: 'ER-2026-06-0301',
      source: 'Booking journal',
      ruleApplied: 'R-330',
      modelVersion: 'pincer-close-2.3.0',
      approver: 'A. Kovalenko',
      systemChange: 'DATEV rebooking posted',
      before: 'Account 6600',
      after: 'Account 6805',
    },
  },
  {
    id: 'a-9003',
    timestamp: '2026-07-23T14:05:00Z',
    action: 'request.sent',
    detail: 'Nordwind Energie SE · June close documentation · portal',
    outcome: 'sent',
    payload: {
      mandate: 'Nordwind Energie SE',
      approver: 'A. Kovalenko',
      systemChange: 'Portal notification delivered',
    },
  },
  {
    id: 'a-9002',
    timestamp: '2026-07-22T09:31:00Z',
    action: 'case.rejected',
    detail: 'Hansa Logistik AG · BK-2026-07-0490 · proposed match rejected',
    outcome: 'rejected',
    payload: {
      mandate: 'Hansa Logistik AG',
      transactionRef: 'BK-2026-07-0490',
      source: 'Bank feed',
      ruleApplied: 'R-310',
      modelVersion: 'pincer-close-2.3.0',
      approver: 'M. Weber',
      systemChange: 'No posting — case returned to agent',
      before: 'Unmatched payment',
      after: 'Unmatched payment (manual follow-up)',
    },
  },
  {
    id: 'a-9001',
    timestamp: '2026-07-21T11:12:00Z',
    action: 'request.sent',
    detail: 'Linde Gastronomie e.K. · Cash report week 29 · Viber',
    outcome: 'sent',
    payload: {
      mandate: 'Linde Gastronomie e.K.',
      approver: 'M. Weber',
      systemChange: 'Viber message delivered',
    },
  },
];
