#!/usr/bin/env node
// `npm run gen:api` — FE-ADR-002 contract pipeline.
//
// Fetches the backend's OpenAPI document, stores a canonical snapshot next to
// the generated TypeScript, runs openapi-typescript, and writes
// api-contract.lock with the backend commit the snapshot was taken from.
//
//   npm run gen:api                                  # http://localhost:8080/openapi.json
//   PINCER_OPENAPI_URL=https://… npm run gen:api
//   npm run gen:api -- --from path/to/openapi.json --commit <sha>
//
// The lock's `pincer_commit` is what CI checks out to rebuild the spec
// offline (see .github/workflows/frontend-ci.yml). Pass --commit, or set
// PINCER_COMMIT, or let the script read it from a sibling checkout at
// ../pincer when present.
import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';
import {
  DEFAULT_OPENAPI_URL,
  LOCK_PATH,
  SCHEMA_PATH,
  SNAPSHOT_PATH,
  canonical,
  loadSpec,
  sha256,
} from './api-contract-lib.mjs';

const args = process.argv.slice(2);
const flag = (name) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
};

const source = flag('--from') ?? process.env.PINCER_OPENAPI_URL ?? DEFAULT_OPENAPI_URL;
let commit = flag('--commit') ?? process.env.PINCER_COMMIT;
if (!commit) {
  try {
    commit = execSync('git -C ../pincer rev-parse HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    commit = 'unknown';
  }
}

const spec = await loadSpec(source);
const text = canonical(spec);
mkdirSync(dirname(SNAPSHOT_PATH), { recursive: true });
writeFileSync(SNAPSHOT_PATH, text);

export async function generate(specObject) {
  const ast = await openapiTS(specObject, {
    alphabetize: true,
    // FastAPI marks Optional fields as nullable; keep `| null` explicit so the
    // FE cannot forget the absence case that every v2+ voice field has.
    defaultNonNullable: false,
  });
  const banner =
    '/* eslint-disable */\n' +
    '// GENERATED by scripts/gen-api.mjs — do not edit. Regenerate with `npm run gen:api`.\n' +
    `// Source: ${spec.info?.title ?? 'OpenAPI'} ${spec.info?.version ?? ''} (pincer ${commit.slice(0, 12)})\n\n`;
  return banner + astToString(ast);
}

writeFileSync(SCHEMA_PATH, await generate(spec));

const lock = {
  pincer_commit: commit,
  spec_sha256: sha256(text),
  api_title: spec.info?.title ?? null,
  api_version: spec.info?.version ?? null,
  paths: Object.keys(spec.paths ?? {}).length,
  generated_at: new Date().toISOString(),
  source: /^https?:\/\//.test(source) ? source : 'file',
};
writeFileSync(LOCK_PATH, JSON.stringify(lock, null, 2) + '\n');

console.log(
  `gen:api ✓ ${lock.paths} paths from ${source} → ${SCHEMA_PATH} (pincer ${commit.slice(0, 12)}, sha ${lock.spec_sha256.slice(0, 12)})`,
);
if (!existsSync('../pincer') && commit === 'unknown') {
  console.warn('gen:api: no backend commit recorded — pass --commit <sha> or set PINCER_COMMIT');
}
